<span style="color: blue;">

## Table of contents:
</span>

* [1. Getting familiar with the dataset](#second-bullet)
** [1.1. Data dictionary](#eight-bullet)
* [2. Exploratory data analysis](#third-bullet)
* [3. Data preparation](#fourth-bullet)

In [26]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [27]:
import warnings
warnings.filterwarnings("ignore")

<span style="color: blue;">

## 1. Getting familiar with the dataset <a class="anchor" id="second-bullet"></a>
    
</span>

In [28]:
pd.set_option('display.max_columns', None)

In [29]:
df = pd.read_csv("air_data.csv")

In [35]:
df.head(20)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,3,4,3,4,3,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,3,1,5,4,5,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,2,4,2,2,2,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,0,2,3,4,4,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,4,3,4,1,2,2,2,2,2,4,2,4,0,20.0,satisfied
5,5,39177,Male,Loyal Customer,16,Business travel,Eco,311,3,3,3,3,5,5,3,5,4,3,1,1,2,5,0,0.0,satisfied
6,6,79433,Female,Loyal Customer,77,Business travel,Business,3987,5,5,5,5,3,5,5,5,5,5,5,4,5,3,0,0.0,satisfied
7,7,97286,Female,Loyal Customer,43,Business travel,Business,2556,2,2,2,2,4,4,5,4,4,4,4,5,4,3,77,65.0,satisfied
8,8,27508,Male,Loyal Customer,47,Business travel,Eco,556,5,2,2,2,5,5,5,5,2,2,5,3,3,5,1,0.0,satisfied
9,9,62482,Female,Loyal Customer,46,Business travel,Business,1744,2,2,2,2,3,4,4,4,4,4,4,5,4,4,28,14.0,satisfied
10,10,47583,Female,Loyal Customer,47,Business travel,Eco,1235,4,1,1,1,5,1,5,3,3,4,3,1,3,4,29,19.0,satisfied
11,11,115550,Female,Loyal Customer,33,Business travel,Business,325,2,5,5,5,1,3,4,2,2,2,2,3,2,4,18,7.0,neutral or dissatisfied
12,12,119987,Female,Loyal Customer,46,Business travel,Business,1009,5,5,5,5,4,5,5,5,5,5,5,5,5,3,0,0.0,satisfied
13,13,42141,Female,Loyal Customer,60,Business travel,Business,451,1,1,4,1,5,5,4,5,5,5,5,3,5,5,117,113.0,satisfied
14,14,2274,Female,Loyal Customer,52,Business travel,Business,925,2,2,2,2,5,5,4,4,4,4,4,3,4,5,10,0.0,satisfied
15,15,22470,Male,Loyal Customer,50,Personal Travel,Eco,83,3,4,0,3,2,0,2,2,4,2,4,4,5,2,5,2.0,neutral or dissatisfied
16,16,124915,Female,Loyal Customer,31,Business travel,Eco,728,2,5,5,5,2,2,2,2,4,3,3,4,3,2,2,0.0,neutral or dissatisfied
17,17,17836,Male,Loyal Customer,52,Personal Travel,Eco Plus,1075,5,4,5,3,4,5,4,4,3,5,5,4,5,4,0,0.0,satisfied
18,18,76872,Female,Loyal Customer,43,Personal Travel,Eco,1927,3,4,3,1,4,4,5,5,5,3,5,4,5,3,0,0.0,neutral or dissatisfied
19,19,64287,Female,Loyal Customer,50,Business travel,Business,3799,5,5,5,5,4,5,4,4,4,5,4,5,4,5,8,0.0,satisfied

In [31]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [34]:
df.nunique()

Unnamed: 0                           103904
id                                   129880
Gender                                    2
Customer Type                             2
Age                                      75
Type of Travel                            2
Class                                     3
Flight Distance                        3821
Inflight wifi service                     6
Departure/Arrival time convenient         6
Ease of Online booking                    6
Gate location                             6
Food and drink                            6
Online boarding                           6
Seat comfort                              6
Inflight entertainment                    6
On-board service                          6
Leg room service                          6
Baggage handling                          5
Checkin service                           6
Inflight service                          6
Cleanliness                               6
Departure Delay in Minutes              466
Arrival Delay in Minutes                472
satisfaction                              2
dtype: int64

<span style="color: blue;">

### 1.1 Data dictionary <a class="anchor" id="eight-bullet"></a>
    
</span>

__Unnamed__ - Row number.

__id__ - Passengers ID.

__Gender__ - Passenger gender.

__Customer Type__ - Is passenger loyal or disloyal.

__Age__ - Passengers age.

__Type of Travel__ - Type of travel.

__Class__  - In-flight class.

__Flight distance__ - Distance travelled.

__Inflight wifi service__ - Passenger's satisfaction with inflight wifi service. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Departure/Arrival time convenient__ - Passenger's satisfaction with arrival time convinience. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Ease of Online booking__ - Passenger's satisfaction with ease of online booking system. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Gate location__  - Passenger's satisfaction with gate location. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Food and drink__ - Passenger's satisfaction with in-flight food and drink. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Online boarding__ - Passenger's satisfaction with online check in system. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Seat comfort__ - Passenger's satisfaction with seat comfort. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Inflight entertainment__ - Passenger's satisfaction with in-flight entertainment. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__On-board service__ - Passenger's satisfaction with on-board service. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Leg room service__  - Passenger's satisfaction with leg room service. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Baggage handling__ - Passenger's satisfaction with baggage handling. There are 5 levels. 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Checkin service__ - Passenger's satisfaction with check-in service. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Inflight service__ - Passenger's satisfaction with in-flight service. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfied.

__Cleanliness__ - Passenger's satisfaction with cleanliness of the plane. There are 6 levels. 0 - No opinion, 1 - Very dissatisfied, 2 - Dissatisfied, 3 - Neutral, 4 - Satisfied, 5 - Very satisfie

__Departure Delay in Minutes__ - Was the flight late to depart.

__Arrival Delay in Minutes__ - Was the flight late to arrive.

__satisfaction__ - Overall flight satisfaction.

<span style="color: blue;">

## 2. Exploratory data analysis <a class="anchor" id="third-bullet"></a>
    
</span>

In [39]:
df.duplicated().value_counts()

False    129880
dtype: int64

In [40]:
df.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             393
satisfaction                           0
dtype: int64

In [42]:
df["Arrival Delay in Minutes"].value_counts

<bound method IndexOpsMixin.value_counts of 0         44.0
1          0.0
2          0.0
3          6.0
4         20.0
          ...
129875     0.0
129876     0.0
129877    14.0
129878     0.0
129879     0.0
Name: Arrival Delay in Minutes, Length: 129880, dtype: float64>

In [43]:
unique_values_counts = df["Arrival Delay in Minutes"].value_counts(dropna=False)
print(f"Unique values and their counts: \n{unique_values_counts}")

Unique values and their counts:
0.0      72753
1.0       2747
2.0       2587
3.0       2442
4.0       2373
         ...
454.0        1
391.0        1
315.0        1
418.0        1
369.0        1
Name: Arrival Delay in Minutes, Length: 473, dtype: int64

In [51]:
missing_values = df["Arrival Delay in Minutes"].tolist()
missing_values

[44.0,
 0.0,
 0.0,
 6.0,
 20.0,
 0.0,
 0.0,
 65.0,
 0.0,
 14.0,
 19.0,
 7.0,
 0.0,
 113.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 49.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 13.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 68.0,
 1.0,
 70.0,
 12.0,
 68.0,
 10.0,
 0.0,
 0.0,
 4.0,
 177.0,
 3.0,
 55.0,
 90.0,
 0.0,
 2.0,
 4.0,
 0.0,
 0.0,
 32.0,
 0.0,
 0.0,
 0.0,
 46.0,
 0.0,
 0.0,
 4.0,
 0.0,
 57.0,
 0.0,
 3.0,
 6.0,
 0.0,
 0.0,
 0.0,
 0.0,
 47.0,
 40.0,
 0.0,
 0.0,
 0.0,
 24.0,
 0.0,
 0.0,
 27.0,
 0.0,
 0.0,
 0.0,
 20.0,
 0.0,
 52.0,
 0.0,
 0.0,
 0.0,
 20.0,
 0.0,
 17.0,
 0.0,
 11.0,
 34.0,
 0.0,
 95.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 66.0,
 113.0,
 2.0,
 13.0,
 0.0,
 7.0,
 24.0,
 0.0,
 0.0,
 2.0,
 6.0,
 0.0,
 0.0,
 0.0,
 4.0,
 0.0,
 0.0,
 40.0,
 11.0,
 8.0,
 17.0,
 0.0,
 10.0,
 86.0,
 0.0,
 0.0,
 8.0,
 0.0,
 88.0,
 0.0,
 46.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 178.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 78.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 18.0,
 0.0,
 0.0,
 0.0,
 0.0,
 72.0,
 41.0,
 0.0,
 12.0,
 91.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 4.0,
 0.0,
 0.0,
 6.0,
 35.0,
 0.0,
 16.0,
 25.0,
 77.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 4.0,
 0.0,
 0.0,
 94.0,
 0.0,
 0.0,
 163.0,
 16.0,
 0.0,
 0.0,
 102.0,
 42.0,
 1.0,
 0.0,
 49.0,
 4.0,
 0.0,
 0.0,
 0.0,
 0.0,
 15.0,
 0.0,
 3.0,
 0.0,
 0.0,
 25.0,
 9.0,
 0.0,
 0.0,
 15.0,
 32.0,
 11.0,
 72.0,
 0.0,
 13.0,
 0.0,
 0.0,
 4.0,
 85.0,
 0.0,
 23.0,
 15.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 88.0,
 9.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 28.0,
 0.0,
 0.0,
 0.0,
 0.0,
 16.0,
 14.0,
 0.0,
 30.0,
 0.0,
 44.0,
 9.0,
 41.0,
 0.0,
 20.0,
 0.0,
 7.0,
 6.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 71.0,
 5.0,
 19.0,
 3.0,
 0.0,
 0.0,
 79.0,
 0.0,
 251.0,
 0.0,
 151.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 17.0,
 38.0,
 0.0,
 5.0,
 0.0,
 0.0,
 0.0,
 0.0,
 12.0,
 30.0,
 0.0,
 65.0,
 0.0,
 65.0,
 4.0,
 10.0,
 10.0,
 62.0,
 1.0,
 0.0,
 0.0,
 0.0,
 21.0,
 1.0,
 0.0,
 17.0,
 68.0,
 0.0,
 0.0,
 0.0,
 4.0,
 0.0,
 29.0,
 0.0,
 0.0,
 40.0,
 4.0,
 24.0,
 0.0,
 0.0,
 93.0,
 0.0,
 0.0,
 1.0,
 0.0,
 41.0,
 5.0,
 0.0,
 12.0,
 0.0,
 232.0,
 11.0,
 0.0,
 0.0,
 6.0,
 0.0,
 13.0,
 0.0,
 156.0,
 4.0,
 14.0,
 0.0,
 0.0,
 0.0,
 0.0,
 12.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 19.0,
 0.0,
 0.0,
 5.0,
 0.0,
 0.0,
 38.0,
 32.0,
 1.0,
 117.0,
 0.0,
 0.0,
 0.0,
 27.0,
 0.0,
 0.0,
 94.0,
 29.0,
 14.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 16.0,
 26.0,
 16.0,
 0.0,
 51.0,
 0.0,
 0.0,
 11.0,
 93.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 8.0,
 14.0,
 88.0,
 17.0,
 0.0,
 3.0,
 0.0,
 0.0,
 99.0,
 0.0,
 55.0,
 0.0,
 121.0,
 11.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 6.0,
 117.0,
 71.0,
 0.0,
 0.0,
 0.0,
 0.0,
 75.0,
 63.0,
 5.0,
 0.0,
 75.0,
 0.0,
 0.0,
 14.0,
 11.0,
 55.0,
 0.0,
 0.0,
 0.0,
 92.0,
 0.0,
 0.0,
 0.0,
 20.0,
 0.0,
 11.0,
 7.0,
 0.0,
 44.0,
 0.0,
 0.0,
 0.0,
 12.0,
 0.0,
 0.0,
 0.0,
 7.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 28.0,
 0.0,
 13.0,
 0.0,
 45.0,
 45.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 7.0,
 0.0,
 14.0,
 0.0,
 123.0,
 129.0,
 27.0,
 5.0,
 0.0,
 0.0,
 0.0,
 25.0,
 7.0,
 29.0,
 46.0,
 0.0,
 84.0,
 41.0,
 0.0,
 0.0,
 2.0,
 0.0,
 19.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 5.0,
 19.0,
 0.0,
 nan,
 0.0,
 1.0,
 210.0,
 0.0,
 8.0,
 13.0,
 15.0,
 0.0,
 0.0,
 4.0,
 0.0,
 47.0,
 0.0,
 0.0,
 32.0,
 0.0,
 0.0,
 0.0,
 0.0,
 35.0,
 0.0,
 62.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 51.0,
 10.0,
 0.0,
 1.0,
 0.0,
 100.0,
 22.0,
 0.0,
 58.0,
 147.0,
 0.0,
 14.0,
 0.0,
 3.0,
 0.0,
 123.0,
 8.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 23.0,
 0.0,
 0.0,
 0.0,
 0.0,
 11.0,
 0.0,
 3.0,
 3.0,
 0.0,
 0.0,
 25.0,
 71.0,
 0.0,
 0.0,
 79.0,
 0.0,
 0.0,
 29.0,
 0.0,
 0.0,
 0.0,
 0.0,
 23.0,
 34.0,
 3.0,
 0.0,
 7.0,
 16.0,
 2.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 123.0,
 0.0,
 61.0,
 0.0,
 18.0,
 0.0,
 0.0,
 49.0,
 42.0,
 95.0,
 0.0,
 10.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 275.0,
 0.0,
 0.0,
 40.0,
 0.0,
 8.0,
 0.0,
 6.0,
 29.0,
 2.0,
 0.0,
 0.0,
 0.0,
 9.0,
 14.0,
 0.0,
 0.0,
 0.0,
 4.0,
 46.0,
 14.0,
 79.0,
 0.0,
 0.0,
 8.0,
 0.0,
 0.0,
 0.0,
 57.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 55.0,
 7.0,
 0.0,
 0.0,
 0.0,
 0.0,
 19.0,
 0.0,
 0.0,
 0.0,
 0.0,
 119.0,
 0.0,
 2.0,
 18.0,
 1.0,
 5.0,
 6.0,
 0.0,
 6.0,
 7.0,
 0.0,
 0.0,
 11.0,
 0.0,
 0.0,
 0.0,
 0.0,
 28.0,
 34.0,
 1.0,
 16.0,
 0.0,
 4.0,
 16.0,
 1.0,
 0.0,
 0.0,
 18.0,
 485.0,
 0.0,
 0.0,
 0.0,
 27.0,
 2.0,
 60.0,
 0.0,
 0.0,
 31.0,
 0.0,
 0.0,
 57.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 27.0,
 2.0,
 0.0,
 10.0,
 0.0,
 0.0,
 0.0,
 5.0,
 7.0,
 7.0,
 30.0,
 0.0,
 62.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 28.0,
 0.0,
 0.0,
 11.0,
 0.0,
 0.0,
 11.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 336.0,
 29.0,
 0.0,
 11.0,
 0.0,
 0.0,
 21.0,
 11.0,
 0.0,
 13.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.0,
 0.0,
 0.0,
 0.0,
 7.0,
 47.0,
 0.0,
 0.0,
 4.0,
 12.0,
 0.0,
 0.0,
 21.0,
 0.0,
 6.0,
 52.0,
 17.0,
 128.0,
 0.0,
 0.0,
 48.0,
 46.0,
 0.0,
 0.0,
 97.0,
 0.0,
 13.0,
 29.0,
 0.0,
 11.0,
 0.0,
 0.0,
 0.0,
 18.0,
 0.0,
 0.0,
 11.0,
 5.0,
 0.0,
 0.0,
 4.0,
 12.0,
 4.0,
 0.0,
 0.0,
 12.0,
 0.0,
 29.0,
 0.0,
 0.0,
 3.0,
 2.0,
 156.0,
 0.0,
 0.0,
 0.0,
 0.0,
 46.0,
 20.0,
 0.0,
 5.0,
 14.0,
 55.0,
 69.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 59.0,
 0.0,
 32.0,
 0.0,
 0.0,
 3.0,
 0.0,
 1.0,
 25.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 99.0,
 0.0,
 49.0,
 0.0,
 0.0,
 50.0,
 0.0,
 17.0,
 72.0,
 44.0,
 0.0,
 0.0,
 0.0,
 0.0,
 11.0,
 23.0,
 58.0,
 407.0,
 2.0,
 35.0,
 0.0,
 0.0,
 0.0,
 7.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 97.0,
 0.0,
 48.0,
 0.0,
 0.0,
 15.0,
 11.0,
 13.0,
 0.0,
 5.0,
 0.0,
 5.0,
 54.0,
 0.0,
 0.0,
 0.0,
 0.0,
 29.0,
 0.0,
 0.0,
 15.0,
 43.0,
 18.0,
 0.0,
 0.0,
 35.0,
 8.0,
 0.0,
 0.0,
 12.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 14.0,
 0.0,
 101.0,
 11.0,
 0.0,
 7.0,
 0.0,
 37.0,
 0.0,
 0.0,
 29.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 16.0,
 0.0,
 0.0,
 0.0,
 8.0,
 23.0,
 0.0,
 101.0,
 96.0,
 0.0,
 0.0,
 0.0,
 0.0,
 11.0,
 37.0,
 43.0,
 105.0,
 13.0,
 29.0,
 0.0,
 0.0,
 0.0,
 20.0,
 0.0,
 0.0,
 11.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 29.0,
 0.0,
 19.0,
 82.0,
 0.0,
 8.0,
 114.0,
 138.0,
 191.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 10.0,
 27.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 6.0,
 0.0,
 3.0,
 4.0,
 6.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [49]:
nan_count = pd.isnull(df["Arrival Delay in Minutes"]).sum()
nan_count

393

In [12]:
df.shape

(129880, 25)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed: 0                         129880 non-null  int64
 1   id                                 129880 non-null  int64
 2   Gender                             129880 non-null  object
 3   Customer Type                      129880 non-null  object
 4   Age                                129880 non-null  int64
 5   Type of Travel                     129880 non-null  object
 6   Class                              129880 non-null  object
 7   Flight Distance                    129880 non-null  int64
 8   Inflight wifi service              129880 non-null  int64
 9   Departure/Arrival time convenient  129880 non-null  int64
 10  Ease of Online booking             129880 non-null  int64
 11  Gate location                      129880 non-null  int64
 12  Food and drink                     129880 non-null  int64
 13  Online boarding                    129880 non-null  int64
 14  Seat comfort                       129880 non-null  int64
 15  Inflight entertainment             129880 non-null  int64
 16  On-board service                   129880 non-null  int64
 17  Leg room service                   129880 non-null  int64
 18  Baggage handling                   129880 non-null  int64
 19  Checkin service                    129880 non-null  int64
 20  Inflight service                   129880 non-null  int64
 21  Cleanliness                        129880 non-null  int64
 22  Departure Delay in Minutes         129880 non-null  int64
 23  Arrival Delay in Minutes           129487 non-null  float64
 24  satisfaction                       129880 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 24.8+ MB

In [38]:
df["id"].unique

<bound method Series.unique of 0         19556
1         90035
2         12360
3         77959
4         36875
          ...
129875    94171
129876    73097
129877    68825
129878    54173
129879    62567
Name: id, Length: 129880, dtype: int64>

In [15]:
df.describe()

,Unnamed: 0,id,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
count,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129880.000000,129487.000000
mean,44158.700000,64940.500000,39.427957,1190.316392,2.728696,3.057599,2.756876,2.976925,3.204774,3.252633,3.441361,3.358077,3.383023,3.350878,3.632114,3.306267,3.642193,3.286326,14.713713,15.091129
std,31207.377062,37493.270818,15.119360,997.452477,1.329340,1.526741,1.401740,1.278520,1.329933,1.350719,1.319289,1.334049,1.287099,1.316252,1.180025,1.266185,1.176669,1.313682,38.071126,38.465650
min,0.000000,1.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,16234.750000,32470.750000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000
50%,38963.500000,64940.500000,40.000000,844.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.000000,0.000000,0.000000
75%,71433.250000,97410.250000,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.000000,12.000000,13.000000
max,103903.000000,129880.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1592.000000,1584.000000

In [16]:
df.describe(include=object)

,Gender,Customer Type,Type of Travel,Class,satisfaction
count,129880,129880,129880,129880,129880
unique,2,2,2,3,2
top,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
freq,65899,106100,89693,62160,73452

<span style="color: blue;">

## 3. Data preparation <a class="anchor" id="fourth-bullet"></a>
    
</span>